server:
  port: ${PORT:0}
spring:
  application.name: servicio-productos
  #Para registrarse en eureka se debe enviar un latido de corazón, si deja de transmitirla por mas
  #de 90 segundos se borra
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client.service-url:
    defaultZone: http://localhost:8761/eureka